engines:
  rubocop:
    enabled: true
  brakeman:
    enabled: true
  bundler-audit:
    enabled: true
  scss-lint:
    enabled: true
  codeclimate-coffeelint:
    enabled: true
  fixme:
    enabled: true
ratings:
   paths:
   - app/**
   - lib/**
   - "**.rb"
exclude_paths:
- app/assets/javascripts/**/*
- db/**/*
- config/**/*
- spec/**/*
- vendor/**/*
- ".codeclimate.yml"
- "Capfile"
- "Gemfile"
- "Gemfile.lock"
- "Guardfile"
- "README.md"
- "Rakefile"
