default: &defaults
  # Your push api key, it is possible to set this dynamically using ERB:
  push_api_key: "<%= ENV['APPSIGNAL_PUSH_API_KEY'] %>"

  # Your app's name
  name: "Agile Season"

  # Actions that should not be monitored by AppSignal
  # ignore_actions:
  #   - ApplicationController#isup

  # See http://docs.appsignal.com/gem-settings/configuration.html for
  # all configuration options.

# Configuration per environment, leave out an environment or set active
# to false to not push metrics for that environment.
test:
  <<: *defaults
  active: false

development:
  <<: *defaults
  active: false

production:
  <<: *defaults
  active: true
