development: &defaults
  adapter: postgresql
  encoding: utf8
  database: agileseason_development
  username: agileseason_development
  password: agileseason
  host: localhost
  pool: 100
  timeout: 5000

test:
  <<: *defaults
  database: agileseason_test
  username: agileseason_test
  port: <%= ENV['PORT'] || 5432 %>

production:
  <<: *defaults
